name: Coleta PromoConn

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  coletar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar coleta
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ML_CLIENT_ID: ${{ secrets.ML_CLIENT_ID }}
          ML_CLIENT_SECRET: ${{ secrets.ML_CLIENT_SECRET }}
          ML_REFRESH_TOKEN: ${{ secrets.ML_REFRESH_TOKEN }}
        run: |
          python coletar.py